### ISSUE TITLE
Dataset inquiry

### ISSUE THREAD

**Issue by shwangtangjun** [zhigang-yao/scAMF#1]
Could you provide a download link for the other 22 datasets?

I am aware that 3 datasets are provided in this repository, and the authors have provided the online links in the supplementary information. However, I have encountered the following problems:
1. There are some subtle difference between `EMTAB3321.mat` in this repository and the data from [E-MTAB-3321 online link](https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-3321). The former has 41,428 genes, while the latter has 41,480 genes. I am not sure why they are different.
2. For GSE files, I do not know which file I should download from [GSE36552 online link](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE36552). There are over 20 files available in this link. Moreover, it seems that these files are not directly available for use.
3. Some online links have expired. For example, in the [Pollen online link](https://hemberg-lab.github.io/scRNA.seq.datasets/human/tissues/), the download link is not available anymore. Also, the data statistics is different from this paper, e.g. 23730 genes, 301 cells v.s. 8869 genes, 249 cells.

I have not checked the other datasets, but considering the problems above, I am deeply concerned that I cannot obtain the correct input files used in this paper. Thus, I raise this issue to request the author to share the datasets, preferably in .mat file format..

**Comment by PJSSOD** [comment]
We have sent the 25 datasets to your email. Please kindly check.
